apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fatt
  description: Enables fetching attestations for your binaries or other non OCI package types.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/fatt
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/fatt
    sonarcloud.io/project-key: SEP-ArgusPanoptes_fatt
    sonarcloud.io/enabled: 'true'
    reporting/workflows: '["CodeQL", "Continuous integration"]'
    reporting/target-branch: main
    preproduction/exclude: '["Dependabot.*"]'
    azure.com/organization: argus-panoptes-dev
    azure.com/project: project_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system
  workflowConfig:
    exclude:
      - 'Dependabot Updates'
