apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-registry
  description: Light weight Terraform Registry.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/terraform-registry
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/terraform-registry
    sonarcloud.io/project-key: SEP-ArgusPanoptes_terraform-registry
    sonarcloud.io/enabled: 'true'
    reporting/workflows: '["CodeQL"]'
    reporting/target-branch: main
    preproduction/exclude: '["Dependabot.*"]'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
