apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fatt
  description: Enables fetching attestations for your binaries or other non OCI package types.
  annotations:
    github.com/project-slug: philips-labs/fatt
    backstage.io/source-location: url:https://github.com/philips-labs/fatt
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: philips-labs
  system: payments-system
