apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-registry
  description: Light weight Terraform Registry.
  annotations:
    github.com/project-slug: philips-labs/terraform-registry
    backstage.io/source-location: url:https://github.com/philips-labs/terraform-registry
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: philips-labs
  system: user-management-system
