name: Release workspace

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Name of the Workspace"
        required: true
        type: string
      force_release:
        description: "Force release even if no changesets are present"
        required: false
        type: boolean
  workflow_call:
    inputs:
      force_release:
        description: "Force release even if no changesets are present"
        required: false
        type: boolean
      workspace:
        description: "Name of the Workspace"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.workspace }}

env:
  GITHUB_TOKEN: ${{ github.token }}
  YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  changesets-pr:
    name: Update Version Packages PR for ${{ inputs.workspace }}
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    defaults:
      run:
        working-directory: ./workspaces/${{ inputs.workspace }}
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096
    permissions:
      packages: read
      contents: write
      pull-requests: write
    outputs:
      needs_release: ${{ steps.release_check.outputs.needs_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('workspaces/${0}/**/yarn.lock', inputs.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        run: yarn install --immutable

      - name: Fetch previous commit for release check
        run: git fetch origin '${{ github.event.before }}'

      - name: Check if release
        id: release_check
        if: inputs.force_release != true
        run: node ../../scripts/ci/check-if-release.js
        env:
          WORKSPACE_NAME: ${{ inputs.workspace }}
          COMMIT_SHA_BEFORE: "${{ github.event.before }}"

      - name: Update Version Packages (${{ inputs.workspace }}) PR
        id: changesets-pr
        if: steps.release_check.outputs.needs_release != 'true' || inputs.force_release != true
        uses: backstage/changesets-action@291bfc1f76d1dcfbf967f5810dc0423592eae09a # v2.3.1
        with:
          title: Version Packages (${{ inputs.workspace }})
          cwd: workspaces/${{ inputs.workspace }}
          version: yarn changeset version
          versionBranch: changesets-release/${{ inputs.workspace }}
          skipRootChangelogUpdate: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release workspace ${{ inputs.workspace }}
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    needs: changesets-pr
    if: needs.changesets-pr.outputs.needs_release == 'true' || inputs.force_release == true
    defaults:
      run:
        working-directory: ./workspaces/${{ inputs.workspace }}
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('workspaces/${0}/**/yarn.lock', inputs.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install --immutable

      - name: Compile TypeScript
        run: yarn tsc:full

      - name: Build all packages
        run: yarn build:all

      - name: publish
        run: |
          yarn workspaces foreach --all -v --no-private npm publish --access public --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ github.token }}
